### ISSUE TITLE
Task destroyed

### ISSUE THREAD

**Issue by haxxus** [Lokraan/laughing-chainsaw#4]

**Comment by haxxus** [comment]
Ah i needed to pip install discord.py , great is running now, is there a prefix for command info  ?

**Comment by Lokraan** [comment]
I am currently working on this, issue is with asynchronous processing. Takes too long reading and writing on the market histories file.

**Comment by Lokraan** [comment]
This issue is currently fixed, doesn't have support for RSI though.

Working on a version 2.0 that will add support for RSI and other trading tools.

**Comment by haxxus** [comment]
Great, looking forward very nice work
