### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by haxxus** [Lokraan/laughing-chainsaw#6]
root@vultr:/home/laughing-chainsaw-master# python3.6 crypto-update-bot.py
Logged in? ??
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "crypto-update-bot.py", line 120, in on_ready
    if(market not in market_history):
TypeError: unhashable type: 'dict'

not sure whats happening, it reports a few from binance only then that error

**Comment by Lokraan** [comment]
Sorry, this was some left over RSI code, should be working now.

**Comment by haxxus** [comment]
great :) , is it hard to get that live btc price feed ive seen on other bots under the bot name  next to now watching or now playing, cant find it on any public bot

**Comment by Lokraan** [comment]
I'll add that to v2.0 which should be out within a week, currently preoccupied by finals 😩

**Comment by haxxus** [comment]
awesome :)
